// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mesage.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_Commands int32

const (
	Message_IDENTITY Message_Commands = 0
	Message_LIST     Message_Commands = 1
	Message_MESSAGE  Message_Commands = 2
)

var Message_Commands_name = map[int32]string{
	0: "IDENTITY",
	1: "LIST",
	2: "MESSAGE",
}

var Message_Commands_value = map[string]int32{
	"IDENTITY": 0,
	"LIST":     1,
	"MESSAGE":  2,
}

func (x Message_Commands) String() string {
	return proto.EnumName(Message_Commands_name, int32(x))
}

func (Message_Commands) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5f85569d9677ae07, []int{0, 0}
}

type Message_Bodies int32

const (
	Message_NIL        Message_Bodies = 0
	Message_PLAIN_TEXT Message_Bodies = 3
	Message_JSON       Message_Bodies = 4
)

var Message_Bodies_name = map[int32]string{
	0: "NIL",
	3: "PLAIN_TEXT",
	4: "JSON",
}

var Message_Bodies_value = map[string]int32{
	"NIL":        0,
	"PLAIN_TEXT": 3,
	"JSON":       4,
}

func (x Message_Bodies) String() string {
	return proto.EnumName(Message_Bodies_name, int32(x))
}

func (Message_Bodies) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5f85569d9677ae07, []int{0, 1}
}

type Message struct {
	Command              Message_Commands `protobuf:"varint,1,opt,name=Command,proto3,enum=protocol.Message_Commands" json:"Command,omitempty"`
	Id                   uint64           `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	ConnectedClientIds   []uint64         `protobuf:"varint,3,rep,packed,name=ConnectedClientIds,proto3" json:"ConnectedClientIds,omitempty"`
	RelayTo              []uint64         `protobuf:"varint,4,rep,packed,name=RelayTo,proto3" json:"RelayTo,omitempty"`
	BodyType             Message_Bodies   `protobuf:"varint,5,opt,name=BodyType,proto3,enum=protocol.Message_Bodies" json:"BodyType,omitempty"`
	Body                 []byte           `protobuf:"bytes,6,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f85569d9677ae07, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCommand() Message_Commands {
	if m != nil {
		return m.Command
	}
	return Message_IDENTITY
}

func (m *Message) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetConnectedClientIds() []uint64 {
	if m != nil {
		return m.ConnectedClientIds
	}
	return nil
}

func (m *Message) GetRelayTo() []uint64 {
	if m != nil {
		return m.RelayTo
	}
	return nil
}

func (m *Message) GetBodyType() Message_Bodies {
	if m != nil {
		return m.BodyType
	}
	return Message_NIL
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.Message_Commands", Message_Commands_name, Message_Commands_value)
	proto.RegisterEnum("protocol.Message_Bodies", Message_Bodies_name, Message_Bodies_value)
	proto.RegisterType((*Message)(nil), "protocol.Message")
}

func init() { proto.RegisterFile("mesage.proto", fileDescriptor_5f85569d9677ae07) }

var fileDescriptor_5f85569d9677ae07 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x41, 0x4b, 0x84, 0x40,
	0x14, 0xc7, 0x57, 0x9d, 0x56, 0x79, 0x89, 0x0c, 0xef, 0x34, 0x74, 0x12, 0x4f, 0x42, 0x60, 0x50,
	0xfb, 0x05, 0x76, 0x4d, 0x62, 0xc2, 0xb5, 0x18, 0xe7, 0x50, 0xa7, 0xb0, 0x9d, 0x21, 0x16, 0xd4,
	0x59, 0xd2, 0x8b, 0x1f, 0xaf, 0x6f, 0x16, 0x4e, 0x6b, 0x97, 0x3a, 0xbd, 0xff, 0xe3, 0xff, 0x7b,
	0x8f, 0x1f, 0x84, 0x9d, 0x1e, 0x9a, 0x0f, 0x9d, 0x9d, 0x3e, 0xcd, 0x68, 0x30, 0xb0, 0xe3, 0x60,
	0xda, 0xe4, 0xcb, 0x05, 0x7f, 0xaf, 0x87, 0xb9, 0xc3, 0x0d, 0xf8, 0xb9, 0xe9, 0xba, 0xa6, 0x57,
	0xcc, 0x89, 0x9d, 0x34, 0xba, 0xbd, 0xca, 0x16, 0x2e, 0x3b, 0x33, 0xd9, 0x19, 0x18, 0xc4, 0x82,
	0x62, 0x04, 0x2e, 0x57, 0xcc, 0x8d, 0x9d, 0x94, 0x08, 0x97, 0x2b, 0xcc, 0x00, 0x73, 0xd3, 0xf7,
	0xfa, 0x30, 0x6a, 0x95, 0xb7, 0x47, 0xdd, 0x8f, 0x5c, 0x0d, 0xcc, 0x8b, 0xbd, 0x94, 0x88, 0x7f,
	0x1a, 0x64, 0xe0, 0x0b, 0xdd, 0x36, 0x93, 0x34, 0x8c, 0x58, 0x68, 0x59, 0x71, 0x03, 0xc1, 0xce,
	0xa8, 0x49, 0x4e, 0x27, 0xcd, 0x2e, 0xac, 0x10, 0xfb, 0x2b, 0xb4, 0x33, 0xea, 0xa8, 0x07, 0xf1,
	0x4b, 0x22, 0x02, 0x99, 0x33, 0x5b, 0xc7, 0x4e, 0x1a, 0x0a, 0x9b, 0x93, 0x1b, 0x08, 0x16, 0x71,
	0x0c, 0x21, 0xe0, 0xf7, 0x45, 0x25, 0xb9, 0x7c, 0xa5, 0x2b, 0x0c, 0x80, 0x94, 0xbc, 0x96, 0xd4,
	0xc1, 0x4b, 0xf0, 0xf7, 0x45, 0x5d, 0x6f, 0x1f, 0x0a, 0xea, 0x26, 0xd7, 0xb0, 0xfe, 0x79, 0x8c,
	0x3e, 0x78, 0x15, 0x2f, 0xe9, 0x0a, 0x23, 0x80, 0xe7, 0x72, 0xcb, 0xab, 0x37, 0x59, 0xbc, 0x48,
	0xea, 0xcd, 0x97, 0x8f, 0xf5, 0x53, 0x45, 0xc9, 0xfb, 0xda, 0x4a, 0xdd, 0x7d, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x61, 0x46, 0x79, 0x83, 0x64, 0x01, 0x00, 0x00,
}
